### PR TITLE
Fix sending digest auth sending invalid userhash field

### LINKED ISSUE #1137: Digest auth with `userhash=`, violating RFC
Saw the following exchange, relevant parts of tcpdump capture.

```
[server].http > P1.50154: #####
    HTTP/1.1 401 Unauthorized
    WWW-Authenticate: Digest qop="auth", realm="#####", nonce="#####", algorithm=SHA-256
    Content-Length: 0
    Server: #####
    Connection: close

P1.50164 > [server].http: #####
    GET ##### HTTP/1.1
    Host: [server]
    User-Agent: go-resty/3.0.0-beta.6 (https://resty.dev)
    Accept-Encoding: gzip, deflate
    Authorization: Digest username="#####", realm="#####", nonce="#####", uri="#####", algorithm=SHA-256, qop=auth, nc=#####, cnonce="#####", userhash=, response="#####"
```

Expected: userhash field in Authorization with valid value, or omitted
Observed: userhash with empty value, violating RFC.

### PR DESCRIPTION
**Pull request by issuj**
Fixes #1137

### CODE REVIEW

File: resty_test.go [hunk 1]
```diff
@@ -851,10 +855,19 @@ func authorizationHeaderValid(t *testing.T, r *http.Request, conf *digestServerC
 	}
 
 	assertEqual(t, conf.opaque, pairs["opaque"])
-	assertEqual(t, "true", pairs["userhash"])
 
-	userHash := h(fmt.Sprintf("%s:%s", conf.username, conf.realm))
-	assertEqual(t, userHash, pairs["username"])
+	userhash, userhashReceived := pairs["userhash"]
+	if userhashReceived {
+		assertTrue(t, userhash == "true", "userhash should be 'true' or 'false'")
```
Comment (jeevatkm) [inline resty_test.go]: @issuj I believe, this line should assert either true or false. 
```go
assertTrue(t, userhash == "true", "userhash should be 'true'")
```

**Review by jeevatkm — CHANGES_REQUESTED** [review]
@issuj Thanks for the PR, please check one review comment.

File: resty_test.go (hunk 1 above)
Comment (issuj) [reply resty_test.go]: Sorry, that was unclear. I improved the message, can you see if it's acceptable now?

Between testing for range allowed by RFC, or for exact behavior by the implementation, I chose the latter.

**Review by jeevatkm — APPROVED** [review]
Thanks @issuj for updating PR.
