### PR TITLE
Set ContentLength to 0 when Body is nil

### LINKED ISSUE #671: How to set Content-Lenght=0 with nil Body?
resty v2.7.0
go 1.20

I use the following code to test:

```go
func main() {
	c := resty.New()

	c.SetPreRequestHook(func(c *resty.Client, r *http.Request) error {
		fmt.Println("zzzzzz", r.Body)
		return nil
	})

	c.R().SetContentLength(true).SetBody(nil).Get("http://10.233.32.117:12233")
}
```

I got following on stdout:

```
zzzzz {}
```

It seems that the rawBody is reassigned to `{}`

And I got following on tcpdump:

```
GET / HTTP/1.1
Host: 10.233.32.117:12233
User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
Accept-Encoding: gzip

.....
```

It seems that although I set the `nil` body and `setContentLength=true`，its not working as expected? anything I missed?

### PR DESCRIPTION
**Pull request by praem90**
To address the issue https://github.com/go-resty/resty/issues/671 set `ContentLength` header to 0 when Body is `nil` and `setContentLength` was set to `true`.

Closes #671

### CODE REVIEW

File: middleware.go [hunk 1]
```diff
@@ -166,8 +166,13 @@ func parseRequestBody(c *Client, r *Request) (err error) {
...
 	// by default resty won't set content length, you can if you want to :)
-	if (c.setContentLength || r.setContentLength) && r.bodyBuf != nil {
-		r.Header.Set(hdrContentLengthKey, fmt.Sprintf("%d", r.bodyBuf.Len()))
+	if c.setContentLength || r.setContentLength {
+		if r.bodyBuf != nil {
+			r.Header.Set(hdrContentLengthKey, fmt.Sprintf("%d", r.bodyBuf.Len()))
+		} else {
+			r.Header.Set(hdrContentLengthKey, "0")
+
+		}
```
Comment (jeevatkm) [inline middleware.go:175]: @praem90 when we have true & false block, it better to go for true block first.
```go
if r.bodyBuf == nil {
	r.Header.Set(hdrContentLengthKey, "0")
} else {
	r.Header.Set(hdrContentLengthKey, fmt.Sprintf("%d", r.bodyBuf.Len()))
}
```

**Review by jeevatkm — CHANGES_REQUESTED** [review]
@praem90 Kindly check the PR comment and address.

File: middleware.go (hunk 1 above)
Comment (praem90) [reply middleware.go:174]: Its good to know the little trick and fixed it.

**Review by jeevatkm — APPROVED** [review]
Thanks @praem90
