### PR TITLE
fix: potential wrong total time in trace info when the request is invalid (#1016)

### LINKED ISSUE #1016: The total time in trace info may become MAX_INT64 in some invalid requests
Currently, the request total is calculated by `EndTime` - `DNS Start Time` | `Get Conn Time`:

https://github.com/go-resty/resty/blob/036c5894765c5b60f2c6992b8a1accae124019f7/request.go#L1256-L1260

And in [Go's transport](https://github.com/golang/go/blob/49d6777d87a0abb3eda032da95eff024156835f7/src/net/http/transport.go#L685), it won't call the `GetConn` if the request is invalid(for example: an invalid URL format), so both of `DNS Start Time` | `Get Conn Time` are zero. So it will get MAX_INT64 if we use a valid time to sub the zero time.

### PR DESCRIPTION
**Pull request by git-hulk**
This closes #1016.

### CODE REVIEW

File: request.go [hunk 1]
```diff
@@ -1253,11 +1253,18 @@ func (r *Request) TraceInfo() TraceInfo {
...
 	} else {
-		ti.TotalTime = ct.endTime.Sub(ct.dnsStart)
+		requestStartTime = ct.dnsStart
 	}
+	// DNS start and get conn time may be zero if the request is invalid.
+	// See issue #1016.
+	if requestStartTime.IsZero() {
+		requestStartTime = r.Time
+	}
+	ti.TotalTime = ct.endTime.Sub(requestStartTime)
```
Comment (ccoVeille) [inline request.go]: Maybe it could be rewritten like this then

```go
          // DNS start and get conn time may be zero if the request is invalid, so default one is the request time
          // See issue #1016. 
          requestStartTime := r.Time

          if !ct.dnsStart.IsZero() { 
                 requestStartTime = ct.dnsStart 
          }

          if ct.gotConnInfo.Reused && !ct.getConn.IsZero() { 
                 requestStartTime = ct.getConn 
          } 

         ti.TotalTime = ct.endTime.Sub(requestStartTime)
```

This way if only one of is no zero, it works

Comment (git-hulk) [reply request.go]: @ccoVeille Thank you! I changed the code style like this.

**Review by ccoVeille — APPROVED** [review]

**Review by jeevatkm — APPROVED** [review]
@git-hulk Thanks for the PR. FYI, you have created a PR agianst v3.

**Comment by git-hulk** [comment]
@jeevatkm Thanks for your review.

> FYI, you have created a PR agianst v3.

Yes, I see the default branch is v3, so I submitted the PR targeted at it. I have sent another PR #1018  to backport this to v2(we're using the v2 indeed).
