### PR TITLE
fix: Deepcopy header in createRawRequest

### LINKED ISSUE #1104: 有时候会遇到相同cookie随请求次数不断复制增长
当我的程序跑起来时会小概率的遇到相同cookie发生复制的问题，这个复制会发生在相同的url上
版本是 resty.dev/v3 v3.0.0-beta.6

Image

Image

它最终会增长到cookies(12)，这似乎和client.SetRetryCount(5)有关，当设置为SetRetryCount(3)时最大增长到cookies(8)，然后请求会失败，再次尝试请求时会重新从cookies(2)开始增长

Image

当这个问题发生时，其他相同baseUrl的请求在失败时似乎也会发生cookie复制
使用方法是SetBaseURL(baseURL)，然后请求endpoint
client.SetRetryCount(0)以及request.SetRetryCount(0)后就观察不到cookie复制问题了

### PR DESCRIPTION
**Pull request by Kodecable**
fix #1104

### CODE REVIEW

File: middleware.go [hunk 1]
```diff
@@ -245,7 +246,8 @@ func createRawRequest(c *Client, r *Request) (err error) {
 	r.RawRequest.Close = r.CloseConnection
 
 	// Add headers into http request
-	r.RawRequest.Header = r.Header
+	r.RawRequest.Header = http.Header{}
+	maps.Copy(r.RawRequest.Header, r.Header)
```
Comment (jeevatkm) [inline middleware.go]: @Kodecable we could use clone method here.
```go
r.RawRequest.Header = r.Header.Clone()
```

**Review by jeevatkm — CHANGES_REQUESTED** [review]
@Kodecable Thanks for the PR. Can you check the review comment and update it?

File: middleware.go (hunk 1 above)
Comment (Kodecable) [reply middleware.go]: fixed.

**Review by jeevatkm — DISMISSED** [review]
@Kodecable Thanks for the update.

**Comment by jeevatkm** [comment]
@Kodecable It seems there are test case failures. Can you please check it?

**Comment by jeevatkm** [comment]
@Kodecable, you could apply this test fix using a patch file ([test-fix-clone-hdr.patch](https://github.com/user-attachments/files/24877873/test-fix-clone-hdr.patch)) and update the PR.

**Review by jeevatkm — APPROVED** [review]
